# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
# job-id
  build:
#  machine sur laquelle sont lancées les commandes
    runs-on: ubuntu-latest
    
    steps:
#    accede à l'espace de travail à l'aide de la librairie checkout fournie par github. https://github.com/actions/checkout
    - uses: actions/checkout@v4
    
#    utilise actions/setup-java pour utiliser une version de java 17 fourni par temurin et maven https://github.com/actions/setup-java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
#    permet de lancer des commande https://docs.github.com/fr/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun
    - name: Install internal jars
    #    installer les librairie locales https://maven.apache.org/guides/mini/guide-3rd-party-jars-local.html
      run: mvn install:install-file -Dfile=libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar && mvn install:install-file -Dfile=libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar && mvn install:install-file -Dfile=libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
    - name: Build with Maven
      run: mvn clean install -B
